framework:
    messenger:
        failure_transport: failed

        transports:
            simulation:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: simulation
                        type: fanout
                    queues:
                        simulation_events: ~
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

        routing:
            'App\Message\SimulationMessage': simulation

when@test:
    framework:
        messenger:
            transports:
                simulation: 'in-memory://'
