<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403205722 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE simulation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, topology_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CBDA467BED697DD5 ON simulation (topology_id)');
        $this->addSql('CREATE TABLE simulation_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, latency INT NOT NULL, payload JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, topology_id INT NOT NULL, source_node_id INT NOT NULL, target_node_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D3D3968CED697DD5 ON simulation_event (topology_id)');
        $this->addSql('CREATE INDEX IDX_D3D3968CFD227BF ON simulation_event (source_node_id)');
        $this->addSql('CREATE INDEX IDX_D3D3968C8D6526BC ON simulation_event (target_node_id)');
        $this->addSql('CREATE TABLE topology (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE topology_edge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, simulated_latency INT NOT NULL, failure_rate DOUBLE PRECISION NOT NULL, topology_id INT NOT NULL, source_node_id INT NOT NULL, target_node_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CE901442ED697DD5 ON topology_edge (topology_id)');
        $this->addSql('CREATE INDEX IDX_CE901442FD227BF ON topology_edge (source_node_id)');
        $this->addSql('CREATE INDEX IDX_CE9014428D6526BC ON topology_edge (target_node_id)');
        $this->addSql('CREATE TABLE topology_node (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, position_x DOUBLE PRECISION NOT NULL, position_y DOUBLE PRECISION NOT NULL, config JSON NOT NULL, type VARCHAR(255) NOT NULL, topology_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3EE92F61ED697DD5 ON topology_node (topology_id)');
        $this->addSql('ALTER TABLE simulation ADD CONSTRAINT FK_CBDA467BED697DD5 FOREIGN KEY (topology_id) REFERENCES topology (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE simulation_event ADD CONSTRAINT FK_D3D3968CED697DD5 FOREIGN KEY (topology_id) REFERENCES topology (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE simulation_event ADD CONSTRAINT FK_D3D3968CFD227BF FOREIGN KEY (source_node_id) REFERENCES topology_node (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE simulation_event ADD CONSTRAINT FK_D3D3968C8D6526BC FOREIGN KEY (target_node_id) REFERENCES topology_node (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE topology_edge ADD CONSTRAINT FK_CE901442ED697DD5 FOREIGN KEY (topology_id) REFERENCES topology (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE topology_edge ADD CONSTRAINT FK_CE901442FD227BF FOREIGN KEY (source_node_id) REFERENCES topology_node (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE topology_edge ADD CONSTRAINT FK_CE9014428D6526BC FOREIGN KEY (target_node_id) REFERENCES topology_node (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE topology_node ADD CONSTRAINT FK_3EE92F61ED697DD5 FOREIGN KEY (topology_id) REFERENCES topology (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE simulation DROP CONSTRAINT FK_CBDA467BED697DD5');
        $this->addSql('ALTER TABLE simulation_event DROP CONSTRAINT FK_D3D3968CED697DD5');
        $this->addSql('ALTER TABLE simulation_event DROP CONSTRAINT FK_D3D3968CFD227BF');
        $this->addSql('ALTER TABLE simulation_event DROP CONSTRAINT FK_D3D3968C8D6526BC');
        $this->addSql('ALTER TABLE topology_edge DROP CONSTRAINT FK_CE901442ED697DD5');
        $this->addSql('ALTER TABLE topology_edge DROP CONSTRAINT FK_CE901442FD227BF');
        $this->addSql('ALTER TABLE topology_edge DROP CONSTRAINT FK_CE9014428D6526BC');
        $this->addSql('ALTER TABLE topology_node DROP CONSTRAINT FK_3EE92F61ED697DD5');
        $this->addSql('DROP TABLE simulation');
        $this->addSql('DROP TABLE simulation_event');
        $this->addSql('DROP TABLE topology');
        $this->addSql('DROP TABLE topology_edge');
        $this->addSql('DROP TABLE topology_node');
    }
}
